name: Calculator CI/CD
on:
  push:
    branches: 
        - main
        - feature-workflow-enhancements

  pull_request:
    branches: 
    - main

  workflow_dispatch: # this is for creating a button in Github for triggering the workflow manually

  schedule:
    - cron: "*/5 * * * *" #change minutes to 0 to run on every hour 
  
  workflow_run:
    
jobs:
  hello:  #New job added to print hello message #Assignment work
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message 
      run: echo "Hello Everyone"  

  build-calculator: # job name , we can give any name here
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Setup Code
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Run lint
      run: npm run lint
    
    - name: Build Project
      run: echo "Building application"

    - name: Deploy Project
      run: echo "Deploy Succesfully"

    # New jobs added for assignment by Chaitali
    - name: Show Node version
      run: node -v

    - name: Show NPM version
      run: npm --version

    - name: Show Event
      run: 'echo "Event type: ${{ github.event_name }}"'

    - name: Show Date
      run: 'echo "Date: $(date)"'
      
  nightly-report:
    runs-on: ubuntu-latest 
    # This job will run only when the schedule trigger is used
    if: github.event_name=='schedule' || github.event_name == 'workflow_dispatch'

    steps:
    
    - name: Show Event
      run: echo "Triggered by ${{ github.event_name }}"

    - name: Generate Report
      run: echo "Generating Report"

  
